### PR TITLE
New ViaSat-3 sync word :D

### PR DESCRIPTION
**Pull request by Marhmarchi**
New sync word used on ViaSat-3 TLM.

### CODE REVIEW

**Comment by Aang23** [comment]
Do you have any data to confirm this? Is this true for all links?

**Comment by Marhmarchi** [comment]
Yes I do!

Sorry for the late answer. I don't know if its for all links, but they changed for the 12.2 GHz one.

The baseband data is from @KentuckyFriedData https://drive.proton.me/urls/2DZ7WT5JP4#y5RkIfjBgbcr

Here is a small bin file that I demodulated with GNU Radio and used to find the sync word https://drive.google.com/file/d/1CgXWau_lvvIcOfZDf1kt7NTg_74X0Zkd/view?usp=sharing

And here is all the data from one of the baseband demodulated with SatDump after changing the sync word in the pipelines https://drive.google.com/file/d/1LFK9g1S8AfulMdMn8o_vVzr7h2h7IEXO/view?usp=sharing

**Comment by Aang23** [comment]
It seems fine, but your sync is inverted.

**Comment by Aang23** [comment]
*and slightly shifted according to the CRC at the end.

The correct sync is 0xfaf3203b. I would perhaps suggest adding an option list to change between both options, in case it is not permanent or on all links.

**Comment by Marhmarchi** [comment]
I must've done something wrong on GNU Radio, but I changed the sync word and added a new pipeline for the 12.2 GHz link. If there are any changes on the others I'll make a new PR with the updates so we only have one pipeline.

**Comment by Marhmarchi** [comment]
Nothing on the other links, just the 12.2 GHz, maybe because its moving to APAC?

**Comment by Aang23** [comment]
Hard to tell, but definitely some onboard confog change.

**Pull request merged**
