### PR TITLE
Pipeline display name tweaks

### PR DESCRIPTION
**Pull request by sgcderek**
Pipeline display names tweaked to all adhere to the same format;

 - Satellite/series name using the capitalization and grammar of its operator or best English translation
 - Downlink name, if there is no "defined" name or it's a multi-purpose generic link then radio band name ("band" instead of "Band" as per IEEE)
 - If there are multiple pipelines that would fit the same name, then symbol rate is displayed
 - If the above is still the case then the modulation follows

This was enough to cover all the current pipelines quite well. There's some exceptions like `ViaSat-3 TT&C (11.7 GHz)` that mentions the specific frequency because it would be otherwise identical to `ViaSat-3 TT&C (12.2 GHz)`. I can't think of a better way to differentiate the two, as both are considered TT&C by ViaSat and have the same symbol rate, but this still fits in well into the overall pipeline naming.

### CODE REVIEW

**Comment by Marhmarchi** [comment]
Well, IMHO taking out whether a pipeline is TLM, DUMP or DB is not a good thing, it'll be counter-intuitive as you don't know what is coming down just by the name. An example is FORMOSAT-7, it only dumps and not having this information will probably annoy people that they didn't see anything from the sat, but this is due to the downlink being dumps only. 

Other than that, I think a good portion of the changes are great, but IMO we should maintain what type of data you're getting, not just what speed it is. 

image

**Comment by Marhmarchi** [comment]
Another example is SAOCOM, it only gives you the TLM and it only dumps in Argentina, so not having it wouldn't be specific on whether you can or can't receive it just by searching for the sat.

**Comment by JVital2013** [comment]
Just my two cents: I love the idea of standardizing it, but I agree that TLM, DUMP or DB should be visible somewhere - perhaps at the end of each pipeline?

To avoid making the names too long, maybe we can keep it the way @sgcderek did it, and add a new "description" string to each pipeline that can show in a tooltip when pointed to in the list. That would give us some more freedom to provide details on a particular pipeline. Thoughts?

**Comment by Marhmarchi** [comment]
> Just my two cents: I love the idea of standardizing it, but I agree that TLM, DUMP or DB should be visible somewhere - perhaps at the end of each pipeline?
> 
> 
> 
> To avoid making the names too long, maybe we can keep it the way @sgcderek did it, and add a new "description" string to each pipeline that can show in a tooltip when pointed to in the list. That would give us some more freedom to provide details on a particular pipeline. Thoughts?

I think that's a great idea! I also thought about something like that, but for me looks like a good way to avoid confusion and also make them clearer!

**Comment by sgcderek** [comment]
Did not mean to close this but I agree with this;

> Just my two cents: I love the idea of standardizing it, but I agree that TLM, DUMP or DB should be visible somewhere - perhaps at the end of each pipeline?
> 
> To avoid making the names too long, maybe we can keep it the way @sgcderek did it, and add a new "description" string to each pipeline that can show in a tooltip when pointed to in the list. That would give us some more freedom to provide details on a particular pipeline. Thoughts?

Potentially having the pipelines grouped by satellite type would also make them more compact when not searching for a particular keyword, in either case the scope of the changes needed would be its own PR anyway

**Comment by Aang23** [comment]
Been quite busy in the last little while so sorry if I'm only now getting to reply!

Overall, I approve and very much appreciate the idea. Pipelines were kinda added "on the fly" as of now and it really meant any sort of logic in the naming has been lost.

I honestly already quite like what you did already, and I'd suggest re-opening it as to merge it. However as @Marhmarchi and @JVital2013 suggested already keeping some basic information about the downlink where applicable seems useful, however I'm not sure if @JVital2013's idea of adding a system - at least straight away is such a good idea at least for now.

IMHO there's an expectation the user somewhat knows what he's searching for. SatDump is meant to be intuitive enough, but you kinda should know what you're looking at decoding in the first place too, so I'm left wondering if such a system to "classify" per type (eg, worlwide-DB-only) etc really makes sense, as this is also something a better documentation covering the same thing could do better. If we're going with such a system for real, I'd push it further and even add an "info" section to eg, specify where a specific dump occurs etc - that'd be going in the same direction as in the viewer with composite documentation, so it's not that out of line either to be honest.

Otherwise, more in line with what was done here, perhaps the general guideline could be about the same, but with an added "tag", such as `SAOCOM 1A/1B S-band (Dump)` or if needed `BlueWalker 3 S-band (512k/Dump)` or similar. Maybe that'd be a decent compromise?

**Pull request closed without merging**
