### PR TITLE
Add Enable/Disable all layers buttons, lock-out projection buttons with zero active layers

### PR DESCRIPTION
**Pull request by mpentler**
This PR was based off my work with large layer sets, sometimes 30+ at a time. Sometimes you genuinely do want to disable ALL of the layers before reselecting new ones from scratch in a different area of the world. Sometimes you want to enable just one layer out of a set to make an image, but hate having to manually click on EVERY inactive layer to turn them all back on.

This change fixes this issue and also gets rid of the hack that always ensures that one layer is selected. This was apparently to protect against crashes, but adding code to lockout the projection buttons if no layers are active in the layer set gets around this.

Happy to take suggestions to change bits of this or improve it, but I am struggling to think of anything I have changed that is "game-breaking" and a few brief tests on Windows worked fine for me with buttons enabling/disabling as required.

### CODE REVIEW

**Comment by mpentler** [comment]
One problem I can see: the code for determining the tooltips for the buttons when generating projections will have two conditions pass if there's no projection layers in the set (because active_layers will also be 0).

This may need handling specifically in those conditional if statements after each of the two buttons - I will test it tomorrow.

**Comment by mpentler** [comment]
I have added the above discussed change and the correct tooltips are now displayed. I think this is ready but invite comments. Jamie and I had talked about how this approach was probably better than hacking around a potential crash by doing something a user hasn't asked the app to do or been informed about (ie, ensuring always 1 layer is active).

**Comment by JVital2013** [comment]
Hey, sorry for sitting on this! I do want to get this merged ASAP, but wanted to focus on bugs first before the 1.2.2 release. Now that that's out of the way, I should have this merged in 2-3 days after some holiday stuff.

Thanks for the work!

**Comment by mpentler** [comment]
Cool beans. Definitely want to check I've put the right logic in the right place and done things the right way.

**Comment by mpentler** [comment]
Idea: lock out All button when all layers are active, lock out None button when no layers are active?

**Comment by mpentler** [comment]
@JVital2013 latest commit seems to make the All/None buttons grey out correctly! I'd say this is ready to go, pending any alterations you wish to make for where the var is declared. Also please check if replicating the code up top is the best way to fix the issue of the buttons not updating until the layer panel is expanded. If that is all ok then I'd say it's ready!

**Comment by JVital2013** [comment]
I only patched up a few things, overall very nice. Thanks!

**Pull request merged**
