### PR TITLE
Add TIP telemetry decoder

### PR DESCRIPTION
**Pull request by thomasdouwes**
Dumps the telemetry values from the TIP subcoms into a JSON file with timestamps. Also dumps the Solar array telemetry from Analog subcom 2 and the AVHRR Scan Motor Current from Analog subcom 1 (16 sec), but that might only be correct for NOAA-15.  

I think the row buffering could cause the last telemetry rows to get missed if the TIP ends without a new row starting, also if a specific frame is missed. I'm not sure how else to keep the JSON timestamps in sync with the values without it though.

### CODE REVIEW

**Comment by Aang23** [comment]
@ZbychuButItWasTaken looks good to me, thoughts?

**Comment by ZbychuButItWasTaken** [comment]
I will check it out later today, on the first glance it looks good though

**Comment by ZbychuButItWasTaken** [comment]
The parity checking in NOAA HRPT isn't really useful anyway, so there isn't much you can do about the errors.
The rest looks fine to me

**Comment by Aang23** [comment]
@ZbychuButItWasTaken should I merge?

**Pull request merged**
